// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaUffjGG2sYMziiCpTz8WrxJlyXHTDQUE',
    appId: '1:861244998658:web:942d35c5b0b0016dae531b',
    messagingSenderId: '861244998658',
    projectId: 'campusconnect-3bf73',
    authDomain: 'campusconnect-3bf73.firebaseapp.com',
    storageBucket: 'campusconnect-3bf73.firebasestorage.app',
    measurementId: 'G-8E3KZJ13VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtw1hzu1RPW1N8TQPEIeSQoMe8oKI45c',
    appId: '1:861244998658:android:4a002f1967d0c8baae531b',
    messagingSenderId: '861244998658',
    projectId: 'campusconnect-3bf73',
    storageBucket: 'campusconnect-3bf73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDSRF7vw7ZZnkd_7cTnrUfv75PjlqxpA',
    appId: '1:861244998658:ios:0bd6b23573001607ae531b',
    messagingSenderId: '861244998658',
    projectId: 'campusconnect-3bf73',
    storageBucket: 'campusconnect-3bf73.firebasestorage.app',
    iosClientId: '861244998658-kfjjqc21raj48t8ocgmjt50bbum32tvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.statefulWidget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDSRF7vw7ZZnkd_7cTnrUfv75PjlqxpA',
    appId: '1:861244998658:ios:0bd6b23573001607ae531b',
    messagingSenderId: '861244998658',
    projectId: 'campusconnect-3bf73',
    storageBucket: 'campusconnect-3bf73.firebasestorage.app',
    iosClientId: '861244998658-kfjjqc21raj48t8ocgmjt50bbum32tvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.statefulWidget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaUffjGG2sYMziiCpTz8WrxJlyXHTDQUE',
    appId: '1:861244998658:web:4fd1a00ccf839b7eae531b',
    messagingSenderId: '861244998658',
    projectId: 'campusconnect-3bf73',
    authDomain: 'campusconnect-3bf73.firebaseapp.com',
    storageBucket: 'campusconnect-3bf73.firebasestorage.app',
    measurementId: 'G-T1VE085RZX',
  );
}
